#define RES_CLIENT               256
#define WND_CNR                  257
#define ICO_YEAR                 258
#define ICO_MONTH                259
#define M_VIEW                   260
#define MI_ICONVIEW              261
#define MI_TREEVIEW              262
#define MI_DETAILVIEW            263
#define MI_ARRANGE               264
#define M_SELECT                 265
#define MI_SELECTALL             266
#define MI_DESELECTALL           267
#define MI_EXIT                  268
