.include "rc.h"
:userdoc.
:h1 res=&EXTHELP_CLIENT..Help
:p.Extended help for client window
:h1 res=&KEYSHELP_CLIENT..Help
:p.Keys help for client window
:h1 res=&HELP_M_FILE..Help
:p.Help for :hp2.File:ehp2. pulldown
:h1 res=&HELP_MI_BOX..Help
:p.Help for :hp2.Message box:ehp2. menu item
:h1 res=&HELP_MI_EXIT..Help
:p.Help for :hp2.Exit:ehp2. menu item
:h1 res=&HELP_MSG_TEST..Help
:p.Message box help
:euserdoc.
