#define RES_CLIENT               256
#define M_FILE                   257
#define MI_BOX                   258
#define MI_EXIT                  259

#define MSG_TEST                 512

#define SUBHELP_CLIENT           128
#define EXTHELP_CLIENT           192
#define KEYSHELP_CLIENT          256
#define HELP_M_FILE              M_FILE
#define HELP_MI_BOX              MI_BOX
#define HELP_MI_EXIT             MI_EXIT
#define HELP_MSG_TEST            MSG_TEST
